name: integration-tests
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      GCP_KEY_FILE: ${{ secrets.GCP_KEY_FILE }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        architecture: [ 'x64' ]
    steps:
      # SET UP JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - run: java -version

      - run: mvn --version

      - run : mkdir ~/lib

      #BUILD HAZELCAST SNAPSHOT
      - uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast
          ref: refs/heads/master
          path: hazelcast

      - name: Build hazelcast jar
        run: |
          cd hazelcast
          mvn clean install -DskipTests
          cp hazelcast/target/hazelcast*SNAPSHOT.jar ~/lib/hazelcast.jar

      # BUILD HAZELCAST GCP SNAPSHOT
      - uses: actions/checkout@v2
        with:
          path: hazelcast-gcp

      - name: Build hazelcast-gcp jar
        run: |
          cd hazelcast-gcp
          mvn clean install -DskipTests
          cp target/hazelcast-gcp-*-SNAPSHOT.jar ~/lib/hazelcast-gcp.jar

      #BUILD TERRAFORM
      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create unique prefix for resources
        run: |
          sed -i -e "s/SET_PREFIX/\"${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}\"/g" hazelcast-gcp/.github/terraform/terraform.tfvars

      - name: Add project ID terraform.tfvars
        run: |
          project_id=$(echo $GCP_KEY_FILE | grep -Po '"project_id":\s"\K[-a-zA-Z0-9]+')
          sed -i -e "s~SET_PROJECT_ID~\"${project_id}\"~g"  hazelcast-gcp/.github/terraform/terraform.tfvars

      - name: Create GCP credentials file
        run: |
          touch hazelcast-gcp/.github/terraform/gcp_key_file.json
          echo $GCP_KEY_FILE > hazelcast-gcp/.github/terraform/gcp_key_file.json

      - name: Terraform Init
        run: cd hazelcast-gcp/.github/terraform && terraform init

      - name: Terraform Format
        run: cd hazelcast-gcp/.github/terraform  && terraform fmt

      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: " "

      - name: Install public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub
          known_hosts: " "

      #   - id: plan
      #     run: cd hazelcast-gcp/terraform && terraform plan

      - name: Terraform Apply
        run: |
          cd hazelcast-gcp/.github/terraform  && terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ always() }}
        run: |
          cd hazelcast-gcp/.github/terraform  && terraform destroy -auto-approve
